### ISSUE TITLE
Container name clashses

### ISSUE THREAD

**Issue by flyte** [StackStorm/st2-docker#109]
I already have a container called `redis` on my machine, so I can't run this as well. Could you please update the container names `mongo`, `rabbitmq`, `postgres`, `redis` to something stackstorm specific? `st2redis` or similar?

Normally docker compose sets a prefix for all of the container names - not sure why it's not doing it now?

**Comment by shusugmt** [comment]
+1

@warrenvw We need to check through all documents and fix the reference if it's using fixed name for container refs. I guess there might be something like `docker exec -it stackstorm bash`, which should be `docker-compose exec stackstorm bash`

**Comment by warrenvw** [comment]
Early on, there was a desire by the team to keep the names short. As you may know, we override the default using the `container_name` instruction in `docker-compose.yml`. It's not ideal since it doesn't work in an environment where more than one of a particular container exists.

> Because Docker container names must be unique, you cannot scale a service beyond 1 container if you have specified a custom name. Attempting to do so results in an error.

(ref: https://docs.docker.com/compose/compose-file/#container_name)

I'll try to spend some time by early next week to submit a PR which addresses this issue. In all likelihood, just renaming the hardcoded container names. We can revisit the use of `container_name` in the future.
