### ISSUE TITLE
stackstorm container does not stop when sent SIGTERM

### ISSUE THREAD

**Issue by warrenvw** [StackStorm/st2-docker#12]
Per https://docs.docker.com/compose/faq/, `docker-compose down` sends SIGTERM to all its containers. If after 10 seconds any are still running, then it sends them a SIGKILL. All containers except `stackstorm` (and sometimes `postgres`) stop within 3 seconds. After 10 seconds, `stackstorm` is still running. `docker-compose` sends it a SIGKILL.

Determine why `stackstorm` container either does not respect SIGTERM or takes too long to stop.. and then fix.

**Comment by warrenvw** [comment]
`/sbin/init` ignores SIGTERM... and does not pass signals to children.

**Comment by armab** [comment]
This is by design, upstart `init` PID1 process shouldn't stop on SIGKILL and it will probably re-exec itself on SIGTERM, same with `systemd` and probably any other init.
See: https://unix.stackexchange.com/questions/7441/can-root-kill-init-process which clarifies the topic.

When considering moving to one group of processes (service) per container, see `dumb-init` (https://github.com/Yelp/dumb-init) which solves the problem:
> `dumb-init` is a simple process supervisor and init system designed to run as PID 1 inside minimal container environments. It spawns command as a child process, saving from possible problems with handling signals.

Also hit that before: https://github.com/StackStorm/st2-dockerfiles/issues/24


As noted before, normal init system and `service start/stop` is not the right way to run under the Docker and you'll have more than that problems in future when diving into mechanics. So I'd assume current working state as good enough for the demo `all-in-one` Docker container.

**Comment by armab** [comment]
Also, really great article about the matter:
https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html

**Comment by warrenvw** [comment]
Closing this issue.
