### ISSUE TITLE
Move away from Ubuntu Trusty before the EOL date (April 2019)

### ISSUE THREAD

**Issue by jeking3** [StackStorm/st2-docker#151]
Ubuntu Trusty is not supported past April 2019.  It would be wise to start moving to Ubuntu Bionic now.

**Comment by jdmeyer3** [comment]
The move to Ubuntu Bionic will not be possible until StackStorm supports MongoDB v4.0 (currently supports v3.4).Reference Stackstorm/st2-packages#554 for Bionic support and  Stackstorm/st2#4098 for Mongodb upgrade.

**Comment by jjm** [comment]
The Python version in Ubuntu Trusty is really quite far behind and I'm just been having problems installing `pdpyras` via `pip` as it requires at least `2.7.10` and the StackStorm docker image is running `2.7.6`.

Moving up to `xenial` would be useful, as Bionic support may be some time away.

**Comment by armab** [comment]
Current all-in-one "demo" Docker image is based on Ubuntu Trusty because of the reasons to keep/start all the services in one container with help of the init system (good for demo, bad for prod). See related https://github.com/StackStorm/st2-docker/issues/29 why it can't be moved to other init like systemd.

For `xenial` and images supporting one service per container natively (good for prod), you may want to look at https://github.com/stackstorm/st2-dockerfiles, which were just released a few days ago as part of K8s work https://github.com/StackStorm/stackstorm-ha we're doing now, but not announced yet.
They're available/deployed to https://hub.docker.com/r/stackstorm/ (`st2api`, `st2auth`, etc. for every stackstorm service). There will be an announcement/update at https://stackstorm.com/blog/ in a few days, so stay tuned.

**Comment by jdmeyer3** [comment]
@armab I've been working on a xenial all-in-one image that works without running in privileged mode. Would creating a PR to bring it into the repo so other developers can develop against the all-in-one image be something you would consider or is that a hard no?

**Comment by armab** [comment]
@jdmeyer3 while the all-in-one Docker is considered a "demo" approach, it doesn't mean users don't need it.

So yes, absolutely. Contributions are very welcome :+1: 

Depending on code, amount of workarounds and stability, proved to be working under different systems we may accept it or not, but it still might be helpful for someone else.
systemd in Docker is an old topic and there might be improvements with time, - we're open to re-consider old decisions if there are better solutions.

**Comment by armab** [comment]
For update, see https://stackstorm.com/2018/10/10/stackstorm-ha-in-kubernetes-beta-community-update/ which includes new st2 community Dockerfiles based on `Ubuntu Xenial`. From the blog:

>  The new Dockerfiles are based on Ubuntu Xenial and define granular resources like ports, volumes, users per container. This ensures better security and makes it very clear what each container can access. We aim to follow 12 factor app, docker dev and dockerfile best practices. For example, containers are ephemeral and immutable, they’re smaller in size, everything is logged to stdout/stderr and we use one service per container to strive the production-level expectations.

Repository: https://github.com/stackstorm/st2-dockerfiles
