### ISSUE TITLE
git bug 

### ISSUE THREAD

**Issue by dennisgreater** [StackStorm/st2-docker#189]
**Describe the problem**

git clone is not possible from inside from the command line and from the cli. I have tried to cone the repo but this is a bug in ubuntu trusty. 

 -it st2-docker_stackstorm_1 bash
root@43b8c4c9a6e5:/# git clone https://git.secrethost.nl/Datapunt/Openstack.git
Cloning into 'Openstack'...
fatal: unable to access 'https://git.datapunt.amsterdam.nl/Datapunt/Openstack.git/': gnutls_handshake() failed: Handshake failed
root@43b8c4c9a6e5:/# 

**Versions**
 - Host OS: [e.g. latest docker version]
 - docker: [e.g. 18.09.7
 - stackstorm/stackstorm image: latest docker

**To Reproduce**

**Comment by armab** [comment]
Looks like related to https://askubuntu.com/questions/186847/error-gnutls-handshake-failed-when-connecting-to-https-servers meaning `git` is really old on Ubuntu14.
There are some workarounds described in the above link.

The root cause is that Ubuntu14 is old and should be removed: https://github.com/StackStorm/st2-docker/issues/151
