### ISSUE TITLE
Simplify or document network configuration of docker-compose

### ISSUE THREAD

**Issue by greenmoss** [StackStorm/st2-docker#231]
**Describe the problem**
The current `docker-compose.yml` contains two defined networks, plus `dns_search: .` statements on all containers except for st2client.

I needed DNS resolution on my Stackstorm jobs, and this configuration confounded me. I was able to get it to work by commenting out/removing all network definitions (e.g. switching to default network), and commenting out/removing all `dns_search: .` lines (e.g. switching to default DNS resolution behavior).

So given that it appears to work fine without the extra networks/dns_search, and that adding those actively breaks external DNS resolution, some documentation would be great! I wasn't even able to determine what `dns_search: .` does, other than to know that without it everything is broken.

Alternately, if nobody knows why those are there, should the be removed? It would simplify the `docker-compose.yml` file, as well as enabling external DNS lookups

**Versions**
 - Host OS: Ubuntu 20.04
 - docker: Docker version 20.10.2, build 2291f61
 - docker-compose: docker-compose version 1.29.2, build 5becea4c
 - stackstorm version: st2 3.5.0, on Python 3.6.9

**To Reproduce**
* `docker-compose up -d`
* `docker exec -it st2-docker_st2stream_1 bash`
* `python3`
* `import socket`
* `socket.gethostbyname('mongo')` # should work
* `socket.gethostbyname('google.com')` # broken
* `docker-compose down`
* edit `docker-compose.yml`
* remove all `networks` and `dns_search` lines
* save/exit
* `docker-compose up -d`
* `docker exec -it st2-docker_st2stream_1 bash`
* `python3`
* `import socket`
* `socket.gethostbyname('mongo')` # should work
* `socket.gethostbyname('google.com')` # should work

**Comment by greenmoss** [comment]
Hmm, seems I was mistaken. If I run `docker-compose down` then `up -d`, all resolution starts breaking. The container names are all hard coded to end with a `.`?

**Comment by stevemuskiewicz** [comment]
@greenmoss I came across a similar issue yesterday though my underlying container platform is [Fedora CoreOS](https://getfedora.org/coreos) - apparently when FCOS upgraded to 35 it broke DNS resolution in my `st2actionrunner` container as well (probably as a result of FCOS changing its DNS resolver to use systemd-resolved)

I found that removing the `dns_search: .` entry for all of the st2* service entries in `docker-compose.yml` was sufficient to get DNS working again.  I didn't need to change any of the `networks` entries in the docker compose file either.

It's not entirely clear to me what the `dns_search: .` entry is intended to do in the context of the st2 services setup (although for me prior to FCOS updating it didn't appear to negatively impact anything).  I found a [very recently asked question on SO](https://stackoverflow.com/questions/70160664/in-docker-compose-what-is-the-effect-purpose-of-dns-search) about this one but the current "answer" to me doesn't seem to clarify anything further.

**Comment by ytjohn** [comment]
Hi.  I'm mostly to blame for the current docker-compose.yml. About 2 years ago, I took it from a single monolithic container and made it use the 1PPC container from st2-dockerfiles, same as what is used in stackstorm-ha kubernetes. 

I'll try to help out with the dns bit, and then explain the networking portions as best I can from memory.

## DNS Issues

The DNS resolution issue happens quite a bit, and not just with the stackstorm. Docker has an embedded dns server. If you're in a container, you'll see`127.0.0.11` in /etc/resolv.conf. When your "host" OS is running either dnsmasq or systemd-resolv, the host's /etc/resolv will point to `127.0.0.53`. This actually usually works fine. But then at some point, possibly after a network change, it breaks for apparently no reason. I can restart systemd-resolve and docker and it's still broken. I can even `docker-compose down --remove-orphans` which gives me a blank slate, including recreating the public/private networks.

The breakage isn't all at once. It can break for one container, but still be working on another. You'll notice that containers can resolve other container names on their network, but not external names. A DNS request inside the container to 127.0.0.11 will work for internal names, but if it has to reach out to the 127.0.0.53 ip for an answer, that fails. But eventually, all of the containers will have broken DNS. If a container happens to still be working, restarting it will pretty much ensure it stops working.

There are two fixes that have worked for me.  The first is rebooting which resets all the docker to systemd resolver issues. But that's not ideal during a workday. The second fix I've found that works is updating the /etc/resolv.conf on the host.  I remove the symlink, then create a new /etc/resolv.conf file with known good nameservers.  Then I restart docker and DNS works happily inside the containers. This would not be ideal if  your host is a laptop that roams from network, and you like having the network's router providing DNS, but in most cases if you put in 8.8.8.8 / 1.1.1.1 or similar, it will work no matter what network you're on.

## Multiple Networks

The public and private networks was from a "best practices" perspective, though it might not really matter here. Almost all the st2*, mongo, redis containers are on a "private" network with no ports exposed. Then the st2web container is on both public and private, and exposes web (80/443) on public network.  That's close to how you would typically deploy it on a production like environment, so I had chosen to emulate that.

## dns_search: .

It has been a while, but here is what I remember.  If you hop into st2actionrunner and `dig mongo`, then it will resolve "mongo" to the container's IP without doing mongo.company.com or otherwise.  If you don't set this `dns_search: .`, then whatever the host has in search in their /etc/resolv.conf will get put into your container's /etc/resolv.conf.

For instance, st2client does not have it set.  On my machine, I have `search localdomain`, but in other places, I might have `search private.company.com company.com`. When you do that, the search ends up in your container and a dns lookup of "st2web" could search `st2web.private.company.com.` instead of `st2web.`.  Putting `dns_search: .`  into the docker-compose changes your search line to ".". 

```
cat /etc/resolv.conf
search private.company.com company.com
nameserver 127.0.0.11
options edns0 trust-ad ndots:0
```

**HOWEVER** - I now realize this is really outdated in docker.  Since at least 2017 docker does this thing now where it adds "ndots:0" to the options. When ndots:0 is there, the search line is ignored. If you search on st2web, the DNS resolvers add a dot to the end (`st2web.`) and it doesn't matter what the search line has.

The `dns_search: .` can be removed, and in fact has no impact on DNS at all inside the containers.



I hope this clears up some confusion.

**Comment by stevemuskiewicz** [comment]
@ytjohn Thanks for the detailed explanation!  That does help explain some of the weird "intermittent" DNS breakage I think.  And I was wondering why `st2client` didn't have a `dns_search` setting...
I'll submit a PR to just remove `dns_search: .` from the docker-compose.yml file since it seems like it is not really relevant any longer.

(BTW I wouldn't say you're "to blame" for the current docker-compose - it has served me well in quickly spinning up st2 test environments so *thank you* for your contributions! 😀 )
